routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 * Landing Page
 */
Route::get('/', 'LandingController@index')->name('landing');

/*
 * Contact Form
 */
Route::get('/contact', 'LandingController@contact')->name('contact');
Route::post('/email', 'LandingController@email')->name('email');

/*
 * Terms of use and privacy policy
 */
Route::get('/privacy-policy', 'LandingController@privacy')->name('privacy');
Route::get('/terms-of-use', 'LandingController@terms')->name('terms');

/*
 * User login, register, reset password and forgot password routes
 */
Auth::routes();

/*
 * Authenticate email routes
 */
Route::get('/verify', 'LandingController@verify')->name('verify');
Route::get('/verify/token/{token}', 'Auth\VerificationController@verify')->name('auth.verify');
Route::get('/verify/resend/', 'Auth\VerificationController@resend')->name('auth.verify.resend');

/*
 * Guest section after successful login or registration
 */
Route::get('/home', 'Frontend\HomeController@index')->name('home');

/*
 * Guest section after successful login or registration display courses
 */
Route::get('/library/courses', 'LandingController@courses')->name('frontend.courses');

/*
 * Guest section after successful login or registration display courses
 */
Route::get('/library/{course}/chapters', 'Frontend\HomeController@chapters')->name('frontend.courses.chapters');

/*
 * User profile section
 */
Route::get('/profile', 'Frontend\UserController@profile')->name('frontend.profile');

/*
 * Edit user email form
 */
Route::post('/editemail', 'Frontend\UserController@editemail')->name('frontend.editemail');

/*
 * Edit user email form
 */
Route::post('/editpassword', 'Frontend\UserController@editpassword')->name('frontend.editpassword');

/*
 * Edit user avatar
 */
Route::post('/editavatar', 'Frontend\UserController@editavatar')->name('frontend.editvatar');


/*
 * Edit profile section
 */
Route::patch('/editprofile', 'Admin\UserController@editprofile')->name('editprofile');

/*
 * Admin and Teacher section
 */
Route::middleware('is_teacher')->group(function() {

    //Admin main page
    Route::get('/admin', 'Admin\AdminController@index')->name('admin');

    //Admin courses page control
    Route::resource('courses', 'Admin\CourseController');

    //Admin chapters page control
    Route::resource('chapters', 'Admin\ChapterController');

    //Admin quizzes page control
    Route::resource('quizzes', 'Admin\QuizController');

    //Get current content
    Route::post('/currentcontent', 'Admin\AdminController@currentcontent')->name('currentcontent');
});

/*
 * Only Admin section
 */
Route::middleware('is_admin')->group(function() {

    //Admin users page control
    Route::resource('users','Admin\UserController')->except([
        'create', 'store', 'show'
    ]);

    Route::post('/teacherpending', 'Admin\AdminController@teacherpending')->name('teacherpending');

});

resources/views/layouts/includes/admin/footer.blade.php
</div>
<!-- /#wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fa fa-angle-up"></i>
</a>

<!-- Modals-->
@include('layouts.includes.admin.modals.logout')

<!-- Custom scripts for all pages-->
<script src="{{ asset('js/admin/app.js') }}"></script>

</body>

</html>

resources/views/layouts/includes/admin/header.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{{ config('app.name', 'Laravel') }} administration dashboard panel">
    <meta name="author" content="Reactive Ninjas">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:600|Ubuntu+Mono" rel="stylesheet">

    <title>{{ $title }}</title>

    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Styles -->
    <link href="{{ asset('css/admin/app.css') }}" rel="stylesheet">

    <!-- CK editor -->
    <script src="{{ asset('js/admin/plugins/ckeditor/ckeditor.js') }}"></script>

</head>

<body id="page-top" @if(isset($pageID)) data-page-id="{{ $pageID }}" @endif>

<nav class="navbar navbar-expand bg-danger static-top">

    <a class="navbar-brand mr-1 text-white" href="{{ url('/admin') }}">
        <img src="{{ asset('images/logo.svg') }}" alt="CodingNinja" width="200" class="coding-ninja-logo">
    </a>

    <!-- Navbar -->
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link text-white dropdown-toggle" href="#" id="userDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                @if($user = \Illuminate\Support\Facades\Auth::user())
                    @if($user->avatar['avatar'])

                        <img width="30px" src="{{ asset('storage/avatars/' . $user->avatar['avatar'] . '?' . $user->avatar['id']) }}" alt="User Avatar SVG">

                        @else

                        <img width="30px" src="{{ asset('images/avatar.svg') }}" alt="User Avatar SVG">

                    @endif
                @endif
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{{url('/')}}" target="_blank">Landing Page</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{route('frontend.profile')}}">Profile</a>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
            </div>
        </li>
    </ul>

</nav>

<div id="wrapper">

resources/views/layouts/includes/admin/sidebar.blade.php
<!-- Sidebar -->
<ul class="sidebar navbar-nav">
    <li class="nav-item">
        <a class="nav-link" href="{{ url('/admin') }}">
            <i class="fa fa-fw fa-home"></i>
            <span>Dashboard</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-fw fa-graduation-cap"></i>
            <span>Courses</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="coursesDropdown">
            <a class="dropdown-item" href="{{ route('courses.create') }}">Create New Course</a>
            <a class="dropdown-item" href="{{ url('/courses') }}">View All Courses</a>
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-fw fa-clipboard"></i>
            <span>Chapters</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="coursesDropdown">
            <a class="dropdown-item" href="{{ route('chapters.create') }}">Create New Chapter</a>
            <a class="dropdown-item" href="{{ url('/chapters') }}">View All Chapters</a>
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-fw fa-file"></i>
            <span>Quizzes</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="coursesDropdown">
            <a class="dropdown-item" href="{{ route('quizzes.create') }}">Create New Quiz</a>
            <a class="dropdown-item" href="{{ url('/quizzes') }}">View All Quizzes</a>
        </div>
    </li>
    @if(\Illuminate\Support\Facades\Auth::user()->isAdmin())
        <li class="nav-item">
            <a class="nav-link" href="{{ url('/users') }}">
                <i class="fa fa-fw fa-users"></i>
                <span>Users</span></a>
        </li>
    @endif
</ul>