routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 * Landing Page
 */
Route::get('/', 'LandingController@index')->name('landing');

/*
 * Contact Form
 */
Route::get('/contact', 'LandingController@contact')->name('contact');
Route::post('/email', 'LandingController@email')->name('email');

/*
 * Terms of use and privacy policy
 */
Route::get('/privacy-policy', 'LandingController@privacy')->name('privacy');
Route::get('/terms-of-use', 'LandingController@terms')->name('terms');

/*
 * User login, register, reset password and forgot password routes
 */
Auth::routes();

/*
 * Authenticate email routes
 */
Route::get('/verify', 'LandingController@verify')->name('verify');
Route::get('/verify/token/{token}', 'Auth\VerificationController@verify')->name('auth.verify');
Route::get('/verify/resend/', 'Auth\VerificationController@resend')->name('auth.verify.resend');

/*
 * Guest section after successful login or registration
 */
Route::get('/home', 'Frontend\HomeController@index')->name('home');

/*
 * Guest section after successful login or registration display courses
 */
Route::get('/library/courses', 'LandingController@courses')->name('frontend.courses');

/*
 * Guest section after successful login or registration display courses
 */
Route::get('/library/{course}/chapters', 'Frontend\HomeController@chapters')->name('frontend.courses.chapters');

/*
 * User profile section
 */
Route::get('/profile', 'Frontend\UserController@profile')->name('frontend.profile');

/*
 * Edit user email form
 */
Route::post('/editemail', 'Frontend\UserController@editemail')->name('frontend.editemail');

/*
 * Edit user email form
 */
Route::post('/editpassword', 'Frontend\UserController@editpassword')->name('frontend.editpassword');

/*
 * Edit user avatar
 */
Route::post('/editavatar', 'Frontend\UserController@editavatar')->name('frontend.editvatar');


/*
 * Edit profile section
 */
Route::patch('/editprofile', 'Admin\UserController@editprofile')->name('editprofile');

/*
 * Admin and Teacher section
 */
Route::middleware('is_teacher')->group(function() {

    //Admin main page
    Route::get('/admin', 'Admin\AdminController@index')->name('admin');

    //Admin courses page control
    Route::resource('courses', 'Admin\CourseController');

    //Admin chapters page control
    Route::resource('chapters', 'Admin\ChapterController');

    //Admin quizzes page control
    Route::resource('quizzes', 'Admin\QuizController');

    //Get current content
    Route::post('/currentcontent', 'Admin\AdminController@currentcontent')->name('currentcontent');
});

/*
 * Only Admin section
 */
Route::middleware('is_admin')->group(function() {

    //Admin users page control
    Route::resource('users','Admin\UserController')->except([
        'create', 'store', 'show'
    ]);

    Route::post('/teacherpending', 'Admin\AdminController@teacherpending')->name('teacherpending');

});

app/Chapter.php
<?php

namespace CodingNinja;

use Illuminate\Database\Eloquent\Model;

class Chapter extends Model
{
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'created_at', 'updated_at'
    ];

    public function course()
    {
        return $this->belongsTo(Course::class);
    }

    public function quizzes()
    {
        return $this->hasMany(Quiz::class);
    }
}

app/Http/Controllers/Admin/ChapterController.php
<?php

namespace CodingNinja\Http\Controllers\Admin;

use CodingNinja\Chapter;
use CodingNinja\Course;
use Illuminate\Http\Request;
use CodingNinja\Http\Controllers\Controller;

class ChapterController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('is_teacher');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $chapters = Chapter::all();
        return view('admin.chapters.index', compact('chapters'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $courses = Course::all();
        return view('admin.chapters.create', compact('courses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|string',
            'course_id' => 'required',
            'content' => 'required'
        ]);

        $chapter = new Chapter();
        $chapter['title'] = $request->get('title');
        $chapter['course_id'] = $request->get('course_id');
        $chapter['slug'] = str_slug($chapter['title'], '-');
        $chapter['content'] = $request->get('content');
        $chapter->save();

        return redirect('/chapters')->with('success', 'Chapter has been added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $chapter = Chapter::find($id);
        $courses = Course::all();
        return view('admin.chapters.edit', compact('chapter', 'courses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required|string',
            'course_id' => 'required',
            'content' => 'required'
        ]);

        $chapter = Chapter::find($id);
        $chapter['title'] = $request->get('title');
        $chapter['course_id'] = $request->get('course_id');
        $chapter['slug'] = str_slug($chapter['title'], '-');
        $chapter['content'] = $request->get('content');
        $chapter->save();

        return redirect('/chapters')->with('success', 'Chapter has been updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $chapter = Chapter::find($id);
        $chapter->delete();

        return redirect('/chapters')->with('success', 'Chapter has been deleted successfully');
    }
}

resources/views/admin/chapters/create.blade.php
@extends('layouts.admin', ['title' => 'Create Chapter | ' . config('app.name'), 'pageID' => 'chapters' ])


@section('content')

        <div class="container">
        <div class="card">
            <h3 class="card-header text-center font-weight-bold text-uppercase py-4">Create New Chapter</h3>
            <div class="card-body">
                <form action="{{ route('chapters.store') }}" method="POST">
                    {{ csrf_field() }}
                    <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                        <label for="title">Title</label>
                        <input id="title" type="text" name="title" class="form-control" value="{{ old('title') }}">
                        @if ($errors->has('title'))
                            <span class="help-block">
                                <strong>{{ $errors->first('title') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group{{ $errors->has('course_id') ? ' has-error' : '' }}">
                        <label for="course_id">Course</label>
                        <select id="course_id" name="course_id" class="form-control">
                            @foreach($courses as $course)
                                <option class="text-dark" value="{{ $course['id'] }}">{{ $course['title'] }}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('course_id'))
                            <span class="help-block">
                                <strong>{{ $errors->first('course_id') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="slug">Slug</label>
                        <input id="slug" class="form-control rounded-0" name="description" value="Slug will be added automatically" disabled>

                    </div>
                    <div class="form-group{{ $errors->has('content') ? ' has-error' : '' }}">
                        <label for="cont">Content</label>
                        <textarea id="contEditor" class="form-control rounded-0" name="content" rows="10">
                            {{ old('content') }}
                        </textarea>
                        @if ($errors->has('content'))
                            <span class="help-block">
                                <strong>{{ $errors->first('content') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="col-sm-6 offset-sm-3 col-md-4 offset-md-4">
                        <button class="btn btn-primary btn-action">Create</button>
                    </div>
                </form>
            </div>
        </div>
        </div>

@endsection

resources/views/admin/chapters/edit.blade.php
@extends('layouts.admin', ['title' => 'Edit Chapter | ' . config('app.name'), 'pageID' => 'chapters' ])


@section('content')

        <div class="container">
        <div class="card">
            <h3 class="card-header text-center font-weight-bold text-uppercase py-4">Edit Chapter</h3>
            <div class="card-body">
                <form action="{{ route('chapters.update', $chapter['id']) }}" method="POST">
                    {{ csrf_field() }}
                    {{ method_field('PATCH') }}
                    <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                        <label for="title">Title</label>
                        <input id="title" type="text" name="title" class="form-control" value="{{ $chapter['title'] }}">
                        @if ($errors->has('title'))
                            <span class="help-block">
                                <strong>{{ $errors->first('title') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group{{ $errors->has('course_id') ? ' has-error' : '' }}">
                        <label for="course_id">Course</label>
                        <select id="course_id" name="course_id" class="form-control">
                            @foreach($courses as $course)
                                <option class="text-dark" value="{{ $course['id'] }}" @if($chapter['course_id'] == $course['id']) selected @endif>{{ $course['title'] }}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('course_id'))
                            <span class="help-block">
                                <strong>{{ $errors->first('course_id') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="slug">Slug</label>
                        <input id="slug" class="form-control rounded-0" name="description" value="{{ $chapter['slug'] }}" disabled>

                    </div>
                    <div class="form-group{{ $errors->has('content') ? ' has-error' : '' }}">
                        <label for="cont">Content</label>
                        <textarea id="contEditor" class="form-control rounded-0" name="content" rows="10">
                            {{ $chapter['content'] }}
                        </textarea>
                        @if ($errors->has('content'))
                            <span class="help-block">
                                <strong>{{ $errors->first('content') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="col-sm-6 offset-sm-3 col-md-4 offset-md-4">
                        <button class="btn btn-primary btn-action">Update</button>
                    </div>
                </form>
            </div>
        </div>
        </div>

@endsection

resources/views/admin/chapters/index.blade.php
@extends('layouts.admin', ['title' => 'Chapters | ' . config('app.name'), 'pageID' => 'chapters' ])


@section('content')

    @if(session()->get('success'))
        <div class="container">
            <div id="notification" class="alert alert-success text-center">
                {{ session()->get('success') }}
            </div>
        </div>
    @endif

    <!-- Chapters table -->
    <div class="container">
        <div class="card">
            <h3 class="card-header text-center font-weight-bold text-uppercase py-4">Chapters</h3>
            <div class="card-body">
                <div id="table" class="table-editable">
                    <table class="table table-bordered table-responsive-md text-center">
                        <tr>
                            <th class="text-center">ID</th>
                            <th class="text-center">Title</th>
                            <th class="text-center">Slug</th>
                            <th class="text-center">Course</th>
                            <th class="text-center">Edit</th>
                            <th class="text-center">Remove</th>
                        </tr>
                        @foreach($chapters as $chapter)
                            <tr>
                                <td class="pt-3-half" contenteditable="true">{{ $chapter['id'] }}</td>
                                <td class="pt-3-half" contenteditable="true">{{ $chapter['title'] }}</td>
                                <td class="pt-3-half" contenteditable="true">{{ $chapter['slug'] }}</td>
                                <td class="pt-3-half" contenteditable="true">{{ $chapter->course['title'] }}</td>
                                <td>
                                    <a href="{{ route('chapters.edit', $chapter['id']) }}"
                                       class="btn btn-outline-warning btn-sm my-0">Edit</a>
                                </td>
                                <td>
                                    <a href="#" data-toggle="modal" data-target="#deleteModal{{$chapter['id']}}"
                                       class="btn btn-outline-danger btn-sm my-0">Delete</a>
                                </td>
                            </tr>

                            {{--Include delete modal--}}
                            @include('layouts.includes.admin.modals.delete', ['route' => 'chapters.destroy', 'item_id' => $chapter['id'], 'title' => 'chapter'])

                        @endforeach
                    </table>
                </div>
            </div>
        </div>
        <div class="row pagination-links">

        </div>
    </div>

@endsection