routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 * Landing Page
 */
Route::get('/', 'LandingController@index')->name('landing');

/*
 * Contact Form
 */
Route::get('/contact', 'LandingController@contact')->name('contact');
Route::post('/email', 'LandingController@email')->name('email');

/*
 * Terms of use and privacy policy
 */
Route::get('/privacy-policy', 'LandingController@privacy')->name('privacy');
Route::get('/terms-of-use', 'LandingController@terms')->name('terms');

/*
 * User login, register, reset password and forgot password routes
 */
Auth::routes();

/*
 * Authenticate email routes
 */
Route::get('/verify', 'LandingController@verify')->name('verify');
Route::get('/verify/token/{token}', 'Auth\VerificationController@verify')->name('auth.verify');
Route::get('/verify/resend/', 'Auth\VerificationController@resend')->name('auth.verify.resend');

/*
 * Guest section after successful login or registration
 */
Route::get('/home', 'Frontend\HomeController@index')->name('home');

/*
 * Guest section after successful login or registration display courses
 */
Route::get('/library/courses', 'LandingController@courses')->name('frontend.courses');

/*
 * Guest section after successful login or registration display courses
 */
Route::get('/library/{course}/chapters', 'Frontend\HomeController@chapters')->name('frontend.courses.chapters');

/*
 * User profile section
 */
Route::get('/profile', 'Frontend\UserController@profile')->name('frontend.profile');

/*
 * Edit user email form
 */
Route::post('/editemail', 'Frontend\UserController@editemail')->name('frontend.editemail');

/*
 * Edit user email form
 */
Route::post('/editpassword', 'Frontend\UserController@editpassword')->name('frontend.editpassword');

/*
 * Edit user avatar
 */
Route::post('/editavatar', 'Frontend\UserController@editavatar')->name('frontend.editvatar');


/*
 * Edit profile section
 */
Route::patch('/editprofile', 'Admin\UserController@editprofile')->name('editprofile');

/*
 * Admin and Teacher section
 */
Route::middleware('is_teacher')->group(function() {

    //Admin main page
    Route::get('/admin', 'Admin\AdminController@index')->name('admin');

    //Admin courses page control
    Route::resource('courses', 'Admin\CourseController');

    //Admin chapters page control
    Route::resource('chapters', 'Admin\ChapterController');

    //Admin quizzes page control
    Route::resource('quizzes', 'Admin\QuizController');

    //Get current content
    Route::post('/currentcontent', 'Admin\AdminController@currentcontent')->name('currentcontent');
});

/*
 * Only Admin section
 */
Route::middleware('is_admin')->group(function() {

    //Admin users page control
    Route::resource('users','Admin\UserController')->except([
        'create', 'store', 'show'
    ]);

    Route::post('/teacherpending', 'Admin\AdminController@teacherpending')->name('teacherpending');

});

app/User.php
<?php

namespace CodingNinja;

use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use phpDocumentor\Reflection\Types\Iterable_;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableInterface;

class User extends Authenticatable implements AuthenticatableInterface
{
    use Notifiable;

    const ADMIN_TYPE = 'admin';
    const DEFAULT_TYPE = 'default';
    const TEACHER_TYPE = 'teacher';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'username', 'email', 'type', 'verified', 'password', 'linkedin','github','about_me'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'verified'
    ];

    /**
     * Check if user is admin
     *
     * @return bool
     */
    public function isAdmin()    {

        return $this->type === self::ADMIN_TYPE;
    }

    /**
     * Check if user is teacher
     *
     * @return bool
     */
    public function isTeacher()    {

        return $this->type === self::TEACHER_TYPE;
    }


    /**
     * The relation between verificationToken and User
     *
     * @return Relation
     */
    public function verificationToken()
    {
        return $this->hasOne(VerificationToken::class);
    }


    /**
     * Check if user has verified email
     *
     * @return boolean
     */
    public function hasVerifiedEmail()
    {
        return $this->verified;
    }


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function avatar()
    {
        return $this->hasOne(Avatar::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace CodingNinja\Http\Controllers\Admin;


use CodingNinja\Events\TeacherApproved;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use CodingNinja\Http\Controllers\Controller;
use CodingNinja\User;

class UserController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('is_admin');
    }


    /**
     * Show the application users page.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $current_user_id = Auth::user()->id;
        $users = User::where('id', '<>', $current_user_id)->paginate(15); //return all users without current user


        return view('admin.users.index', compact('users'));
    }


    /**
     * Show the application user profile page.
     *
     * @return \Illuminate\Http\Response
     */
    public function editprofile(Request $request)
    {
        $user_id = $request->user()->id;

        $request->validate([
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'username' => 'required|string|max:255',
            'email' => 'required|string|email|max:255',
            'facebook' => 'max:255',
            'instagram' => 'max:255',
            'github' => 'max:255'
        ]);

        $user = User::find($user_id);
        $user['first_name'] = $request->get('first_name');
        $user['last_name'] = $request->get('last_name');
        $user['email'] = $request->get('email');
        $user['facebook'] = $request->get('facebook');
        $user['instagram'] = $request->get('instagram');
        $user['github'] = $request->get('github');
        $user['about_me'] = $request->get('about_me');

        $user->save();

        return back()->with('success', 'Your profile has been updated successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return view('admin.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'username' => 'required|string|max:255',
            'email' => 'required|string|email|max:255',
            'type' => 'required|string'
        ]);

        $user = User::find($id);
        $user['first_name'] = $request->get('first_name');
        $user['last_name'] = $request->get('last_name');
        $user['username'] = $request->get('username');
        $user['email'] = $request->get('email');
        $user['type'] = $request->get('type');


        if($user['type'] === 'teacher') {

            event(new TeacherApproved($user));
            $user['verified'] = true;
        }

        $user->save();


        return redirect('/users')->with('success', 'User has been updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();

        return redirect('/users')->with('success', 'User has been deleted successfully');
    }
}

app/Http/Controllers/Frontend/UserController.php
<?php

namespace CodingNinja\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use CodingNinja\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use CodingNinja\User;
use Illuminate\Support\Facades\Hash;
use CodingNinja\Avatar;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application profile page.
     *
     * @return \Illuminate\Http\Response
     */
    public function profile()
    {
        $user = Auth::user();

        return view('frontend.profile', compact('user'));
    }

    /**
     * Update Email
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function editemail(Request $request)
    {
        $user_id = $request->user()->id;

        $request->validate([
            'email' => 'required|email|max:255'
        ]);

        $user = User::find($user_id);
        $user['email'] = $request->get('email');

        $user->save();

        return back()->with('success', 'Your email was updated successfully!');
    }

    /**
     * Update Password
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function editpassword(Request $request)
    {

        $user_id = $request->user()->id;

        $request->validate([
            'oldpassword' => 'required|max:255',
            'newpassword' => 'required|max:255|min:6'
        ]);

        $user = User::find($user_id);
        $oldpassword = $request->get('oldpassword');
        $newpassword = $request->get('newpassword');

        if(Hash::check($oldpassword, $user['password'])) {

            $user['password'] = Hash::make($newpassword);
            $user->save();

            return back()->with('success', 'Your password was updated successfully!');
        }

        return back()->with('fail', 'Invalid password');
    }

    /**
     * Update Avatar
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function editavatar(Request $request)
    {
        $userid = $request->get('userID');
        $avatarfile = $request->get('avatar');

        $user = User::find($userid);

        if ($user->avatar()) {

            $user->avatar()->delete();
        }

        $avatar = new Avatar();
        $avatar['user_id'] = $userid;
        $avatar['avatar'] = 'avatar' . $userid . '.svg';
        $avatar->save();

        Storage::drive('local')->put('public/avatars/avatar' .  $userid . '.svg', $avatarfile);

        return response()->json(['status' => 200, 'avatar' => $avatar['avatar']]);
    }

}

resources/views/admin/users/edit.blade.php
@extends('layouts.admin', ['title' => 'Edit User | ' . config('app.name'), 'pageID' => 'users' ])


@section('content')

    <div class="main-content">

        <div class="container">
            <div class="card">
                <h3 class="card-header text-center font-weight-bold text-uppercase py-4">Edit User</h3>
                <div class="card-body">
                    <form action="{{ route('users.update', $user['id']) }}" method="POST">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}
                        <div class="form-group{{ $errors->has('first_name') ? ' has-error' : '' }}">
                            <label for="first_name">First Name</label>
                            <input id="first_name" type="text" name="first_name" class="form-control" value="{{ $user['first_name'] }}">
                            @if ($errors->has('first_name'))
                                <span class="help-block">
                                <strong>{{ $errors->first('first_name') }}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('last_name') ? ' has-error' : '' }}">
                            <label for="last_name">First Name</label>
                            <input id="last_name" type="text" name="last_name" class="form-control" value="{{ $user['last_name'] }}">
                            @if ($errors->has('last_name'))
                                <span class="help-block">
                                <strong>{{ $errors->first('last_name') }}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('username') ? ' has-error' : '' }}">
                            <label for="username">First Name</label>
                            <input id="username" type="text" name="username" class="form-control" value="{{ $user['username'] }}">
                            @if ($errors->has('username'))
                                <span class="help-block">
                                <strong>{{ $errors->first('username') }}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email">First Name</label>
                            <input id="email" type="text" name="email" class="form-control" value="{{ $user['email'] }}">
                            @if ($errors->has('email'))
                                <span class="help-block">
                                <strong>{{ $errors->first('email') }}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('type') ? ' has-error' : '' }}">
                            <label for="type">User Type</label>
                            <select id="type" name="type" class="form-control">
                                <option class="text-dark" value="{{ CodingNinja\User::DEFAULT_TYPE }}" @if($user['type'] == CodingNinja\User::DEFAULT_TYPE) selected @endif>{{ ucfirst(CodingNinja\User::DEFAULT_TYPE) }}</option>
                                <option class="text-dark" value="{{ CodingNinja\User::TEACHER_TYPE }}" @if($user['type'] == CodingNinja\User::TEACHER_TYPE) selected @endif>{{ ucfirst(CodingNinja\User::TEACHER_TYPE) }}</option>
                                <option class="text-dark" value="{{ CodingNinja\User::ADMIN_TYPE }}" @if($user['type'] == CodingNinja\User::ADMIN_TYPE) selected @endif>{{ ucfirst(CodingNinja\User::ADMIN_TYPE) }}</option>
                            </select>
                            @if ($errors->has('type'))
                                <span class="help-block">
                                <strong>{{ $errors->first('type') }}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="col-sm-6 offset-sm-3 col-md-4 offset-md-4">
                            <button type="submit" class="btn btn-primary btn-action">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin', ['title' => 'Users | ' . config('app.name'), 'pageID' => 'users' ])


@section('content')

    @if(session()->get('success'))
        <div class="container">
            <div id="notification" class="alert alert-success text-center">
                {{ session()->get('success') }}
            </div>
        </div>
    @endif

    <!-- Courses table -->
    <div class="container">
        <div class="card">
            <h3 class="card-header text-center font-weight-bold text-uppercase py-4">Users</h3>
            <div class="card-body">
                <div id="table" class="table-editable">
                    <table class="table table-bordered table-responsive-md text-center">
                        <tr>
                            <th class="text-center">ID</th>
                            <th class="text-center">First Name</th>
                            <th class="text-center">Last Name</th>
                            <th class="text-center">Username</th>
                            <th class="text-center">Email</th>
                            <th class="text-center">Role</th>
                            <th class="text-center">Edit</th>
                            <th class="text-center">Remove</th>
                        </tr>
                        @foreach($users as $user)
                            <tr>
                                <td class="pt-3-half" contenteditable="true">{{ $user['id'] }}</td>
                                <td class="pt-3-half" contenteditable="true">{{ $user['first_name'] }}</td>
                                <td class="pt-3-half" contenteditable="true">{{ $user['last_name'] }}</td>
                                <td class="pt-3-half" contenteditable="true">{{ $user['username'] }}</td>
                                <td class="pt-3-half" contenteditable="true">{{ $user['email'] }}</td>
                                <td class="pt-3-half" contenteditable="true">{{ $user['type'] }}</td>
                                <td>
                                    <a href="{{ route('users.edit', $user['id']) }}"
                                       class="btn btn-outline-warning btn-sm my-0">Edit</a>
                                </td>
                                <td>
                                    <a href="#" data-toggle="modal" data-target="#deleteModal{{$user['id']}}"
                                       class="btn btn-outline-danger btn-sm my-0">Delete</a>
                                </td>
                            </tr>

                            {{--Include delete modal--}}
                            @include('layouts.includes.admin.modals.delete', ['route' => 'users.destroy', 'item_id' => $user['id'], 'title' => 'user'])

                        @endforeach
                    </table>
                </div>
            </div>
        </div>
        <div class="row pagination-links">
            {{ $users->links() }}
        </div>
    </div>

@endsection

resources/views/admin/users/profile.blade.php
@extends('layouts.admin')

@section('content')

    @if(session()->get('success'))
        <div class="row">
            <div class="col-md-8">
                <div class="alert alert-primary">
                    <button type="button" aria-hidden="true" class="close" data-dismiss="alert" aria-label="Close">
                        <i class="tim-icons icon-simple-remove"></i>
                    </button>
                    <span>{{ session()->get('success') }}</span>
                </div>
            </div>
        </div>
    @endif
    
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">Edit Profile</h5>
                </div>
                <div class="card-body">
                    <form action="{{ route('editprofile') }}" method="post">
                        {{csrf_field()}}
                        {{method_field('PATCH')}}
                        <div class="row">
                            <div class="col-md-6 pr-md-1">
                                <div class="form-group">
                                    <label>First Name</label>
                                    <input type="text" class="form-control" name="first_name" placeholder="First Name" value="{{ $user['first_name'] }}">
                                    @if ($errors->has('first_name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('first_name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6 pl-md-1">
                                <div class="form-group">
                                    <label>Last Name</label>
                                    <input type="text" class="form-control" name="last_name"  placeholder="Last Name" value="{{ $user['last_name'] }}">
                                    @if ($errors->has('last_name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('last_name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-8 pr-md-1">
                                <div class="form-group">
                                    <label>Username</label>
                                    <input type="text" class="form-control" name="username" placeholder="Username" value="{{ $user['username'] }}">
                                    @if ($errors->has('username'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('username') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-4 pl-md-1">
                                <div class="form-group">
                                    <label>Your Role</label>
                                    <input type="text" class="form-control" placeholder="Role" value="{{ $user['type'] }}" disabled>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Email</label>
                                    <input type="email" class="form-control" name="email" placeholder="Email" value="{{ $user['email'] }}">
                                    @if ($errors->has('email'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4 pr-md-1">
                                <div class="form-group">
                                    <label>Facebook</label>
                                    <input type="text" class="form-control" name="facebook" placeholder="Facebook" value="{{ $user['facebook'] }}">
                                </div>
                            </div>
                            <div class="col-md-4 px-md-1">
                                <div class="form-group">
                                    <label>Instagram</label>
                                    <input type="text" class="form-control" name="instagram" placeholder="Instagram" value="{{ $user['instagram'] }}">
                                </div>
                            </div>
                            <div class="col-md-4 pl-md-1">
                                <div class="form-group">
                                    <label>Github</label>
                                    <input type="text" class="form-control" name="github" placeholder="Github" value="{{ $user['github'] }}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label>About Me</label>
                                    <textarea rows="4" cols="80" class="form-control" name="about_me" placeholder="Here can be your description" value="Mike">{{ $user['about_me'] }}</textarea>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-fill btn-primary">Save</button>
                </div>
                </form>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card card-user">
                <div class="card-body">
                    <p class="card-text">
                        <div class="author">
                            <div class="block block-one"></div>
                            <div class="block block-two"></div>
                            <div class="block block-three"></div>
                            <div class="block block-four"></div>
                            <a href="javascript:void(0)">
                                <img class="avatar" src="../assets/img/emilyz.jpg" alt="...">
                                <h5 class="title">{{ $user['username'] }}</h5>
                            </a>
                </div>
                </p>
                <div class="card-description">
                    {{ $user['about_me'] }}
                </div>
            </div>
            <div class="card-footer">
                <div class="button-container">
                    @if($user['facebook'])
                        <button onclick="window.open('{{ url($user['facebook']) }}')" class="btn btn-icon btn-round btn-facebook">
                            <i class="fab fa-facebook"></i>
                        </button>
                    @endif
                        @if($user['instagram'])
                        <button onclick="window.open('{{ url($user['instagram']) }}')" class="btn btn-icon btn-round btn-twitter">
                            <i class="fab fa-instagram"></i>
                        </button>
                        @endif
                            @if($user['github'])
                                <button onclick="window.open('{{ url($user['github']) }}')" class="btn btn-icon btn-round btn-twitter">
                                    <i class="fab fa-github"></i>
                                </button>
                            @endif
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection