routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 * Landing Page
 */
Route::get('/', 'LandingController@index')->name('landing');

/*
 * Contact Form
 */
Route::get('/contact', 'LandingController@contact')->name('contact');
Route::post('/email', 'LandingController@email')->name('email');

/*
 * Terms of use and privacy policy
 */
Route::get('/privacy-policy', 'LandingController@privacy')->name('privacy');
Route::get('/terms-of-use', 'LandingController@terms')->name('terms');

/*
 * User login, register, reset password and forgot password routes
 */
Auth::routes();

/*
 * Authenticate email routes
 */
Route::get('/verify', 'LandingController@verify')->name('verify');
Route::get('/verify/token/{token}', 'Auth\VerificationController@verify')->name('auth.verify');
Route::get('/verify/resend/', 'Auth\VerificationController@resend')->name('auth.verify.resend');

/*
 * Guest section after successful login or registration
 */
Route::get('/home', 'Frontend\HomeController@index')->name('home');

/*
 * Guest section after successful login or registration display courses
 */
Route::get('/library/courses', 'LandingController@courses')->name('frontend.courses');

/*
 * Guest section after successful login or registration display courses
 */
Route::get('/library/{course}/chapters', 'Frontend\HomeController@chapters')->name('frontend.courses.chapters');

/*
 * User profile section
 */
Route::get('/profile', 'Frontend\UserController@profile')->name('frontend.profile');

/*
 * Edit user email form
 */
Route::post('/editemail', 'Frontend\UserController@editemail')->name('frontend.editemail');

/*
 * Edit user email form
 */
Route::post('/editpassword', 'Frontend\UserController@editpassword')->name('frontend.editpassword');

/*
 * Edit user avatar
 */
Route::post('/editavatar', 'Frontend\UserController@editavatar')->name('frontend.editvatar');


/*
 * Edit profile section
 */
Route::patch('/editprofile', 'Admin\UserController@editprofile')->name('editprofile');

/*
 * Admin and Teacher section
 */
Route::middleware('is_teacher')->group(function() {

    //Admin main page
    Route::get('/admin', 'Admin\AdminController@index')->name('admin');

    //Admin courses page control
    Route::resource('courses', 'Admin\CourseController');

    //Admin chapters page control
    Route::resource('chapters', 'Admin\ChapterController');

    //Admin quizzes page control
    Route::resource('quizzes', 'Admin\QuizController');

    //Get current content
    Route::post('/currentcontent', 'Admin\AdminController@currentcontent')->name('currentcontent');
});

/*
 * Only Admin section
 */
Route::middleware('is_admin')->group(function() {

    //Admin users page control
    Route::resource('users','Admin\UserController')->except([
        'create', 'store', 'show'
    ]);

    Route::post('/teacherpending', 'Admin\AdminController@teacherpending')->name('teacherpending');

});

resources/views/admin/courses/create.blade.php
@extends('layouts.admin', ['title' => 'Create Course | ' . config('app.name'), 'pageID' => 'courses' ])


@section('content')

        <div class="container">
        <div class="card">
            <h3 class="card-header text-center font-weight-bold text-uppercase py-4">Create New Course</h3>
            <div class="card-body">
                <form action="{{ route('courses.store') }}" method="POST">
                {{ csrf_field() }}
                    <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                        <label for="title">Title</label>
                        <input id="title" type="text" name="title" class="form-control" value="{{ old('title') }}">
                        @if ($errors->has('title'))
                            <span class="help-block">
                                <strong>{{ $errors->first('title') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="slug">Slug</label>
                        <input id="slug" class="form-control rounded-0" value="Slug will be automatically added" disabled>

                    </div>
                    <div class="form-group{{ $errors->has('content') ? ' has-error' : '' }}">
                        <label for="cont">Content</label>
                        <textarea id="contEditor" class="form-control rounded-0" name="content" rows="10">
                            {{ old('content') }}
                        </textarea>
                        @if ($errors->has('content'))
                            <span class="help-block">
                                <strong>{{ $errors->first('content') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="col-sm-6 offset-sm-3 col-md-4 offset-md-4">
                        <button class="btn btn-primary btn-action">Create</button>
                    </div>
                </form>
            </div>
        </div>
        </div>

@endsection

resources/views/admin/courses/edit.blade.php
@extends('layouts.admin', ['title' => 'Edit Course | ' . config('app.name'), 'pageID' => 'courses' ])


@section('content')

        <div class="container">
        <div class="card">
            <h3 class="card-header text-center font-weight-bold text-uppercase py-4">Edit Course</h3>
            <div class="card-body">
                <form action="{{ route('courses.update', $course['id']) }}" method="POST">
                    {{ csrf_field() }}
                    {{ method_field('PATCH') }}
                    <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                        <label for="title">Title</label>
                        <input id="title" type="text" name="title" class="form-control" value="{{ $course['title'] }}">
                        @if ($errors->has('title'))
                            <span class="help-block">
                                <strong>{{ $errors->first('title') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="slug">Description</label>
                        <input id="slug" class="form-control rounded-0" value="{{ $course['slug'] }}" disabled>
                    </div>
                    <div class="form-group{{ $errors->has('content') ? ' has-error' : '' }}">
                        <label for="cont">Content</label>
                        <textarea id="contEditor" class="form-control rounded-0" name="content" rows="10">
                            {{ $course['content'] }}
                        </textarea>
                        @if ($errors->has('content'))
                            <span class="help-block">
                                <strong>{{ $errors->first('content') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="col-sm-6 offset-sm-3 col-md-4 offset-md-4">
                        <button class="btn btn-primary btn-action">Update</button>
                    </div>
                </form>
            </div>
        </div>
        </div>

@endsection

resources/views/admin/courses/index.blade.php
@extends('layouts.admin', ['title' => 'Courses | ' . config('app.name'), 'pageID' => 'courses' ])


@section('content')

    @if(session()->get('success'))
        <div class="container">
            <div id="notification" class="alert alert-success text-center">
                {{ session()->get('success') }}
            </div>
        </div>
    @endif

    <!-- Courses table -->
    <div class="container">
        <div class="card">
            <h3 class="card-header text-center font-weight-bold text-uppercase py-4">Courses</h3>
            <div class="card-body">
                <div id="table" class="table-editable">
                    <table class="table table-bordered table-responsive-md text-center">
                        <tr>
                            <th class="text-center">ID</th>
                            <th class="text-center">Title</th>
                            <th class="text-center">Slug</th>
                            <th class="text-center">Edit</th>
                            <th class="text-center">Remove</th>
                        </tr>
                        @foreach($courses as $course)
                            <tr>
                                <td class="pt-3-half" contenteditable="true">{{ $course['id'] }}</td>
                                <td class="pt-3-half" contenteditable="true">{{ $course['title'] }}</td>
                                <td class="pt-3-half" contenteditable="true">{{ $course['slug'] }}</td>
                                <td>
                                    <a href="{{ route('courses.edit', $course['id']) }}"
                                       class="btn btn-outline-warning btn-sm my-0">Edit</a>
                                </td>
                                <td>
                                    <a href="#" data-toggle="modal" data-target="#deleteModal{{$course['id']}}"
                                       class="btn btn-outline-danger btn-sm my-0">Delete</a>
                                </td>
                            </tr>

                            {{--Include delete modal--}}
                            @include('layouts.includes.admin.modals.delete', ['route' => 'courses.destroy', 'item_id' => $course['id'], 'title' => 'course'])

                        @endforeach
                    </table>
                </div>
            </div>
        </div>
        <div class="row pagination-links">

        </div>
    </div>

@endsection